# Generated by Django 4.2 on 2025-07-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='calle',
        ),
    ]
