# Generated by Django 4.2 on 2025-08-20 19:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_cliente_calle'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='nombre', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='nombre', unique=True),
            preserve_default=False,
        ),
    ]
