# Generated by Django 4.2 on 2025-08-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='envio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
