# Generated by Django 4.2 on 2025-08-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_pedido_envio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='envio_total',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
