# Generated by Django 4.2 on 2025-08-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_pedido_envio_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_envio_default', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10, verbose_name='Costo de envío general')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
    ]
