# Generated by Django 4.2 on 2025-08-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo_promocion', '0003_alter_promocodigo_descuento'),
        ('web', '0010_delete_configuracionglobal_alter_pedido_envio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='promo_codigo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Codigo_promocion.promocodigo'),
        ),
    ]
