# Generated by Django 4.2 on 2025-08-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_pedido_promo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'Pagado'), ('2', 'Enviado')], default='0', max_length=20),
        ),
    ]
