# Generated by Django 4.2 on 2025-08-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'Pagado'), ('2', 'Enviado')], default='Pendiente', max_length=20),
        ),
    ]
