# Generated by Django 4.2 on 2025-08-22 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo_promocion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_final',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promocodigo',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
