# Generated by Django 4.2 on 2025-08-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo_promocion', '0002_alter_promocodigo_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodigo',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
    ]
