# Generated by Django 4.2 on 2025-08-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo_promocion', '0003_alter_promocodigo_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodigo',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
