# Generated by Django 4.2 on 2025-08-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo_promocion', '0004_alter_promocodigo_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodigo',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
