# Generated by Django 4.2 on 2025-08-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codigo_promocion', '0005_alter_promocodigo_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodigo',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
    ]
